routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Auth::routes(['verify' => true]);


Route::get('user-profile', 'UserProfileController@index');
Route::post('user-profile', 'UserProfileController@store')->name('user-profile');


Route::middleware(['auth','verified','roleCheck:NGO'])->group(function () {

	Route::get('/', 'HomeController@index')->name('home');


	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/volunteers', 'VolunteersController@index')->name('volunteers');
	Route::resource('volunteers', 'VolunteersController');
//	Route::resource('/admin/hazard_prone_area', 'HazardProneAreaController');
	Route::get('/volunteers/{id}/delete', 'VolunteersController@delete');
	Route::resource('stocks', 'StocksController');
	Route::get('/stocks/{id}/delete', 'StocksController@delete');
    Route::get('/stocks/detail/{id}', 'StocksController@show');
	Route::resource('affiliations', 'AffiliationsController');
	Route::get('/affiliations/{id}/delete', 'AffiliationsController@delete');
    Route::get('/affiliations/detail/{id}', 'AffiliationsController@show');



	//NGO Profile
    Route::get('/profile/request-approval', 'Ngo\NgoProfileController@approval');
    Route::get('/profile/create','Ngo\NgoProfileController@create');
    Route::post('/profile/create','Ngo\NgoProfileController@store')->name('profile.store');
    Route::get('/profile/approval/request-update', 'Ngo\NgoProfileController@update_approval');
	Route::resource('profile','Ngo\NgoProfileController');

	//NGO MOU
	Route::resource('mous','Ngo\NgoMouController');
	Route::get('/mou/create','Ngo\NgoMouController@create');
    Route::get('/mou/{id}/delete', 'Ngo\NgoMouController@delete');

	//NGO Projects
	Route::resource('projects','Ngo\NgoProjectsController');
	Route::get('/project/create','Ngo\NgoProjectsController@create');
    Route::get('/noc/approval/request-update', 'Ngo\NgoProjectsController@update_approval');
	Route::get('/project/{id}/delete', 'Ngo\NgoProjectsController@delete');


	//NGO Donors
	Route::resource('donors','Ngo\NgoDonorsController');

	//NGO NOC Requests
	Route::resource('noc-requests','Ngo\NgoNocRequestsController');
    Route::get('/noc-apply/create','Ngo\NgoProjectsController@nocApply');

	//Emergencies Responded
	Route::resource('past-emergencies','Ngo\NgoPastEmergenciesController');
	Route::get('/past-emergency/create','Ngo\NgoPastEmergenciesController@create');
	Route::get('/past-emergency/{id}/delete','Ngo\NgoPastEmergenciesController@delete');
    Route::get('/past-emergency/detail/{id}', 'Ngo\NgoPastEmergenciesController@show');

	//NGO Contact
	Route::resource('ngocontact', 'NgoContactController');
	Route::get('ngocontact/{id}/delete', 'NgoContactController@delete');
    Route::get('ngocontact/detail/{id}', 'NgoContactController@show');

	//Contact For PDMA
	Route::resource('contacpdma', 'ContactPdmaController');
	Route::get('contacpdma/{id}/delete', 'ContactPdmaController@delete');


	// Emergencies
	Route::get('emergencies', 'EmergenciesController@index');
	// Route::get('need-assesment', 'NeedAssesmentController@index');
	Route::resource('need-assesment', 'NeedAssesmentController');
	Route::post('needassesmentresponses', 'NeedAssesmentController@needassesmentresponses')->name('needassesmentresponses');


	//Risk Management
	Route::resource('risk-management', 'RiskManagementController');
	Route::get('risk-management/{id}/delete', 'RiskManagementController@delete');

	//Reaminder
	Route::get('readremainder/{id}', 'HomeController@readremainder')->name('readremainder');


	Route::resource('human-resource', 'HumanResourceController');
	Route::get('/human-resource/{id}/delete', 'HumanResourceController@delete');
	Route::get('/human-resource/detail/{id}', 'HumanResourceController@show');



	//NGO Reporting
	Route::resource('reporting','Ngo\NgoReportingController');
	Route::get('/reporting/create','Ngo\NgoReportingController@create')->name('reporting.new');
	Route::get('/reporting/{id}/delete', 'Ngo\NgoReportingController@delete');


	// Notification Listing
	Route::get('notification','Ngo\NotificationController@index')->name('notification.index');
	Route::get('notification/emergencies','Ngo\NotificationController@emergencies')->name('notification.emergencies');

	// Tehsil Listing
    Route::get('/getTehsils/{id}','AjaxController@getTehsils');
    Route::get('/getUcs/{id}','AjaxController@getUcs');
    Route::get('/getProjectDetail/{id}','AjaxController@getProjectDetail');
    Route::post('accept-terms/{id}','AjaxController@acceptTerms');


});

Route::resource('admin/comments', 'CommentController');

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],

    'namespace'  => 'Admin',
], function () {
	   Route::crud('user', 'UserCrudController');
	   Route::get('dashboard', 'DashboardController@index');

    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
});

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],
], function () {
    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::post('emergency-item/send-emg-notification','AjaxController@sendEmgNotification');
    Route::get('project/show-report-summary/{id}','AjaxController@showSummaryReport');
});

// middleware

app/Models/Stock.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'stocks';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */
    public function getNgoName() {
        if($this->ngo){
            return $this->ngo->name;
        }else{
            return '';
        }
     }

     public function getCatName() {
        if($this->category){
            return $this->category->name;
        }else{
            return '';
        }
     }

     public function getItemName() {
        if($this->type){
            return $this->type->name;
        }else{
            return '';
        }
     }
     public function getlocationName() {
        if($this->location){
            return $this->location->name;
        }else{
            return '';
        }
     }
    public function getptehsilTitle() {
        if($this->tehsil){
            return $this->tehsil->name;
        }else{
            return '';
        }
    }
    public function getucTitle() {
        if($this->uc){
            return $this->uc->name;
        }else{
            return '';
        }
    }
    public function getdistrictTitle() {
        if($this->district){
            return $this->district->name;
        }else{
            return '';
        }
    }
    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    public function ngo()
    {
        return $this->belongsTo('App\User', 'ngo_id', 'id');

    }
    public function category()
    {
        return $this->belongsTo('App\Models\Category_type', 'category_id', 'id');

    }

    public function type()
    {
        return $this->belongsTo('App\Models\Item_type', 'item_type_id', 'id');

    }
    public function location()
    {
        return $this->belongsTo('App\Models\Province', 'location_id', 'id');

    }

    public function district(){
        return $this->belongsTo(District::class,'district_id','id');
    }

    public function tehsil(){
        return $this->belongsTo(Tehsil::class,'tehsil_id','id');
    }

    public function uc(){
        return $this->belongsTo(Uc::class,'uc_id','id');
    }


    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Stocks.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\app\Models\Traits\CrudTrait;

class Stocks extends Model
{
    //
    use CrudTrait;

    protected $fillable = [
        'name', 'category_id', 'quantity', 'item_type_id', 'availability', 'location_id', 'remarks','ngo_id','district_id','tehsil_id','uc_id','office_warehouse_address'
    ];


    public function category()
    {
        return $this->belongsTo('App\Models\Category_type', 'category_id','id');
    }
    public function type()
    {
        return $this->belongsTo('App\Models\Item_type', 'item_type_id', 'id');

    }
    public function location()
    {
        return $this->belongsTo('App\Models\Province', 'location_id', 'id');

    }

    public function district()
    {
        return $this->belongsTo('App\Models\District', 'district_id', 'id');

    }

    public function tehsil()
    {
        return $this->belongsTo('App\Models\Tehsil', 'tehsil_id', 'id');

    }

    public function uc()
    {
        return $this->belongsTo('App\Models\Uc', 'uc_id', 'id');

    }
}

app/Http/Controllers/StocksController.php
<?php

namespace App\Http\Controllers;

use App\Models\NgoProfile;
use Illuminate\Http\Request;
use App\Volunteer;
use Auth;

use App\District;
use App\Province;

use App\Tehsil;
use App\Uc;
use App\Stocks;
use App\Models\Category_type;

use App\Models\Item_type;

class StocksController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Stocks.');
        }
        $Stocks = Stocks::where('ngo_id', $userId)->get();
        return view('Stocks.index', compact('Stocks','ngoProfile'));
    }

    public function create()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Stocks.');
        }
        $Province = Province::get();
        $District = District::get();
        $Tehsil = Tehsil::get();
        $Uc = Uc::get();
        $Category_type = Category_type::get();
        $Item_type = Item_type::get();
        return view('Stocks.add', compact('District','Tehsil','Uc','Category_type','Item_type','Province'));
    }

    public function edit($id)
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Stocks.');
        }
        $Province = Province::get();
        $District = District::get();
        $Tehsil = Tehsil::get();
        $Uc = Uc::get();
        $Stocks = Stocks::where('id', $id)->first();
        $Category_type = Category_type::get();
        $Item_type = Item_type::get();
        return view('Stocks.Edit', compact('Stocks','District','Tehsil','Uc','Category_type','Item_type','Province'));
    }

    public function show($id)
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Stocks.');
        }
        $Stocks = Stocks::where('id', $id)->first();
        return view('Stocks.show', compact('Stocks','ngoProfile'));
    }


    public function store(Request $request)
    {
         $request->validate([
            'name' => 'required',
            'category_id' => 'required',
            'quantity' => 'required',
            'item_type_id' => 'required',
            'location_id' => 'required',
            ]);
        $userId = Auth::id();

        $Stocks = new Stocks([
            'name' => $request->get('name'),
            'category_id' => $request->get('category_id'),
            'quantity' => $request->get('quantity'),
            'item_type_id' => $request->get('item_type_id'),
            'availability' => $request->get('availability'),
            'location_id' => $request->get('location_id'),
            'remarks' => $request->get('remarks'),
            'district_id' => $request->get('district_id'),
            'tehsil_id' => $request->get('tehsil_id'),
            'uc_id' => $request->get('uc_id'),
            'ngo_id' => $userId,
        ]);
       $Stocks->save();

        if($request->submit_type && $request->submit_type == 'save_new'){
            return redirect('/stocks/create')->with('message', 'Saved!');
        }

       return redirect('/stocks')->with('message', 'Saved!');
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'category_id' => 'required',
            'quantity' => 'required',
            'item_type_id' => 'required',
            'location_id' => 'required',
            ]);

        $Stocks = Stocks::find($id);
        $Stocks->name =  $request->get('name');
        $Stocks->category_id =  $request->get('category_id');
        $Stocks->quantity =  $request->get('quantity');
        $Stocks->item_type_id =  $request->get('item_type_id');
        $Stocks->availability =  $request->get('availability');
        $Stocks->location_id =  $request->get('location_id');
        $Stocks->remarks =  $request->get('remarks');
        $Stocks->district_id =  $request->get('district_id');
        $Stocks->tehsil_id =  $request->get('tehsil_id');
        $Stocks->uc_id =  $request->get('uc_id');
        $Stocks->save();
        return redirect('/stocks')->with('message', 'Update successfully!');
    }

    public function delete($id){

        $userId = Auth::id();
        $Stocks = Stocks::where('id', $id)->where('ngo_id',$userId)->first();
        if($Stocks){
            $StocksDelete = Stocks::find($Stocks->id);
            $StocksDelete->delete();

        }

        return redirect('/stocks')->with('message', 'Deleted successfully!');    }
}

resources/views/Stocks/Edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>
                <div class="panel-body">
                    @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div><br />
                                @endif
                    <form action="{{route('stocks.update',$Stocks->id)}}" class="needs-validation" novalidate method="POST" enctype="multipart/form-data">
                        @method('PATCH')

                        @csrf

                        <div class="form-group col-md-6">
                            <label for="category_id">Category *</label>
                            <select required id="category_id" name="category_id" class="form-control">
                                <option value="">Select</option>

                                @foreach ($Category_type as $item)
                                <option value="{{$item->id}}" @if($Stocks->category_id == $item->id)  selected  @endif >{{$item->name}}</option>
                                @endforeach

                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Name" value="{{$Stocks->name}}" name="name">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="quantity">Quantity *</label>
                            <input type="number" class="form-control is_numeric" id="quantity" placeholder="Quantity" value="{{$Stocks->quantity}}" name="quantity">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="item_type_id">Item Type *</label>
                            <select id="item_type_id" required name="item_type_id" class="form-control">
                                <option value="">Select</option>
                                @foreach ($Item_type as $item)
                                <option value="{{$item->id}}" @if($Stocks->item_type_id == $item->id)  selected  @endif >{{$item->name}}</option>
                                @endforeach

                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="availability">Availability</label>
                            <input type="text" class="form-control" id="availability" placeholder="availability" value="{{$Stocks->availability}}"  name="availability">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="location_id">Location *</label>
                            <select required id="location_id" name="location_id" class="form-control">
                                <option value="">Select</option>
                                @foreach ($Province as $item)
                                <option value="{{$item->id}}" @if($Stocks->location_id == $item->id)  selected  @endif >{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="district_id">District *</label>
                            <select required id="district_id" name="district_id" class="form-control">
                                <option value="">Select</option>
                                @foreach ($District as $item)
                                    <option
                                        @if($Stocks->district_id == $item->id)  selected  @endif
                                        value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="tehsil_id">Tehsil *</label>
                            <select required id="tehsil_id" name="tehsil_id" class="form-control">
                                <option value="">Select</option>
                                @foreach ($Tehsil as $item)
                                    <option
                                        @if($Stocks->tehsil_id == $item->id)  selected  @endif
                                        title="{{$item->district->name}}" value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="uc_id">UC *</label>
                            <select required id="uc_id" name="uc_id" class="form-control">
                                <option value="">Select</option>
                                @foreach ($Uc as $item)
                                    <option
                                        @if($Stocks->uc_id == $item->id)  selected  @endif
                                        title="{{$item->tehsil->name}}" value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="office_warehouse_address">Office/Warehouse Address</label>
                            <input type="text" class="form-control" id="office_warehouse_address" placeholder="Office/Warehouse Address" value="{{old('office_warehouse_address',$Stocks->remarks)}}"  name="remarks">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="remarks">Remarks</label>
                            <input type="text" class="form-control" id="remarks" placeholder="remarks" value="{{$Stocks->remarks}}"  name="remarks">
                        </div>

                        <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-default">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('pagespecificscripts')
<script>

    $( function() {
        var $district_id = $('#district_id'),
            $tehsil_id = $('#tehsil_id'),
            $uc_id = $('#uc_id'),
            $ucs = $uc_id.find('option');
        $tehsils = $tehsil_id.find('option');

        $district_id.on('change', function() {
            let selectedTh = $tehsil_id.find('option:selected');
            $tehsil_id.html($tehsils.filter('[title="' + $('#district_id').find(":selected").text() + '"]'));
            $tehsil_id.trigger('change');
            $tehsil_id.val($(selectedTh).val());
        }).trigger('change');
        $tehsil_id.on('change', function() {
            let selectedUc = $uc_id.find('option:selected');
            $uc_id.html($ucs.filter('[title="' + $('#tehsil_id').find(":selected").text() + '"]'));
            $uc_id.trigger('change');
            $uc_id.val($(selectedUc).val());
        }).trigger('change');
        $( "#availability" ).datepicker();
    } );
    </script>
<script>
    // Disable form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {

            // Get the forms we want to add validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
@endsection

resources/views/Stocks/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-12">
        <!-- Advanced Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Stocks
            </div>
            <div class="panel-body">
                @if (session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif


                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Quantity</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($Stocks as $key => $item)
                            <tr class="odd gradeX">
                                <td>{{$item->name}}</td>
                                <td>{{$item->category->name}}</td>
                                <td>{{$item->quantity}}</td>
                                <td>
                                    <a href="{{ url("/stocks/detail/{$item->id}") }}">View</a>
                                    @if((checkProfileApproval() && checkEnableEdit()) || $ngoProfile->user->status === 0 )
                                    <a href="{{ url("/stocks/{$item->id}/edit") }}"> - Edit - </a>
                                    @endif
                                    @if($ngoProfile->user->status === 0 )
                                    - <a href="{{ url("/stocks/{$item->id}/delete") }}">Delete</a>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr class="gradeU">
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!--End Advanced Tables -->
    </div>
</div>

@endsection

@section('pagespecificscripts')
<script>
       $(document).ready(function () {
                $('#dataTables-example').dataTable();
            });
    </script>
@endsection

resources/views/Stocks/show.blade.php
@extends('layouts.app')
{{--@dd($Stocks->category_id)--}}
@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="col-md-6">
                        <h3>Stocks</h3>
                    </div>
                    @if((checkProfileApproval() && checkEnableEdit()) || $ngoProfile->user->status === 0 )
                        <div class="col-md-6 text-right">
                            <a href="{{route('stocks.edit', $Stocks->id)}}">Edit Details</a>
                        </div>
                    @endif
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <p><b>Category:</b> {{$Stocks->category->name}}</p>
                        </div>
                        <div class="col-md-6">
                            <p><b>Name:</b> {{$Stocks->name}}</p>
                        </div>
                        <div class="col-md-6">
                            <p><b>Quantity:</b> {{$Stocks->quantity}}</p>
                        </div>
                        <div class="col-md-6">
                            <p><b>Item Type:</b> {{$Stocks->type->name}}</p>
                        </div>
                        <div class="col-md-6">
                            <p><b>Availability:</b> {{$Stocks->availability}}</p>
                        </div>
                        <div class="col-md-6">
                            <p><b>Location:</b> {{$Stocks->location->name}}</p>
                        </div>
                        @if($Stocks->district)
                        <div class="col-md-6">
                            <p><b>District:</b> {{$Stocks->district->name}}</p>
                        </div>
                        @endif
                        @if($Stocks->tehsil)
                        <div class="col-md-6">
                            <p><b>Tehsil:</b> {{$Stocks->tehsil->name}}</p>
                        </div>
                        @endif
                        @if($Stocks->uc)
                        <div class="col-md-6">
                            <p><b>UC:</b> {{$Stocks->uc->name}}</p>
                        </div>
                        @endif
                        @if($Stocks->office_warehouse_address)
                        <div class="col-md-6">
                            <p><b>Office/Warehouse Address:</b> {{$Stocks->office_warehouse_address}}</p>
                        </div>
                        @endif
                        <div class="col-md-6">
                            <p><b>Remarks:</b> {{$Stocks->remarks}}</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <a href="{{url('/stocks')}}" class="btn btn-default">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection