routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Auth::routes(['verify' => true]);


Route::get('user-profile', 'UserProfileController@index');
Route::post('user-profile', 'UserProfileController@store')->name('user-profile');


Route::middleware(['auth','verified','roleCheck:NGO'])->group(function () {

	Route::get('/', 'HomeController@index')->name('home');


	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/volunteers', 'VolunteersController@index')->name('volunteers');
	Route::resource('volunteers', 'VolunteersController');
//	Route::resource('/admin/hazard_prone_area', 'HazardProneAreaController');
	Route::get('/volunteers/{id}/delete', 'VolunteersController@delete');
	Route::resource('stocks', 'StocksController');
	Route::get('/stocks/{id}/delete', 'StocksController@delete');
    Route::get('/stocks/detail/{id}', 'StocksController@show');
	Route::resource('affiliations', 'AffiliationsController');
	Route::get('/affiliations/{id}/delete', 'AffiliationsController@delete');
    Route::get('/affiliations/detail/{id}', 'AffiliationsController@show');



	//NGO Profile
    Route::get('/profile/request-approval', 'Ngo\NgoProfileController@approval');
    Route::get('/profile/create','Ngo\NgoProfileController@create');
    Route::post('/profile/create','Ngo\NgoProfileController@store')->name('profile.store');
    Route::get('/profile/approval/request-update', 'Ngo\NgoProfileController@update_approval');
	Route::resource('profile','Ngo\NgoProfileController');

	//NGO MOU
	Route::resource('mous','Ngo\NgoMouController');
	Route::get('/mou/create','Ngo\NgoMouController@create');
    Route::get('/mou/{id}/delete', 'Ngo\NgoMouController@delete');

	//NGO Projects
	Route::resource('projects','Ngo\NgoProjectsController');
	Route::get('/project/create','Ngo\NgoProjectsController@create');
    Route::get('/noc/approval/request-update', 'Ngo\NgoProjectsController@update_approval');
	Route::get('/project/{id}/delete', 'Ngo\NgoProjectsController@delete');


	//NGO Donors
	Route::resource('donors','Ngo\NgoDonorsController');

	//NGO NOC Requests
	Route::resource('noc-requests','Ngo\NgoNocRequestsController');
    Route::get('/noc-apply/create','Ngo\NgoProjectsController@nocApply');

	//Emergencies Responded
	Route::resource('past-emergencies','Ngo\NgoPastEmergenciesController');
	Route::get('/past-emergency/create','Ngo\NgoPastEmergenciesController@create');
	Route::get('/past-emergency/{id}/delete','Ngo\NgoPastEmergenciesController@delete');
    Route::get('/past-emergency/detail/{id}', 'Ngo\NgoPastEmergenciesController@show');

	//NGO Contact
	Route::resource('ngocontact', 'NgoContactController');
	Route::get('ngocontact/{id}/delete', 'NgoContactController@delete');
    Route::get('ngocontact/detail/{id}', 'NgoContactController@show');

	//Contact For PDMA
	Route::resource('contacpdma', 'ContactPdmaController');
	Route::get('contacpdma/{id}/delete', 'ContactPdmaController@delete');


	// Emergencies
	Route::get('emergencies', 'EmergenciesController@index');
	// Route::get('need-assesment', 'NeedAssesmentController@index');
	Route::resource('need-assesment', 'NeedAssesmentController');
	Route::post('needassesmentresponses', 'NeedAssesmentController@needassesmentresponses')->name('needassesmentresponses');


	//Risk Management
	Route::resource('risk-management', 'RiskManagementController');
	Route::get('risk-management/{id}/delete', 'RiskManagementController@delete');

	//Reaminder
	Route::get('readremainder/{id}', 'HomeController@readremainder')->name('readremainder');


	Route::resource('human-resource', 'HumanResourceController');
	Route::get('/human-resource/{id}/delete', 'HumanResourceController@delete');
	Route::get('/human-resource/detail/{id}', 'HumanResourceController@show');



	//NGO Reporting
	Route::resource('reporting','Ngo\NgoReportingController');
	Route::get('/reporting/create','Ngo\NgoReportingController@create')->name('reporting.new');
	Route::get('/reporting/{id}/delete', 'Ngo\NgoReportingController@delete');


	// Notification Listing
	Route::get('notification','Ngo\NotificationController@index')->name('notification.index');
	Route::get('notification/emergencies','Ngo\NotificationController@emergencies')->name('notification.emergencies');

	// Tehsil Listing
    Route::get('/getTehsils/{id}','AjaxController@getTehsils');
    Route::get('/getUcs/{id}','AjaxController@getUcs');
    Route::get('/getProjectDetail/{id}','AjaxController@getProjectDetail');
    Route::post('accept-terms/{id}','AjaxController@acceptTerms');


});

Route::resource('admin/comments', 'CommentController');

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],

    'namespace'  => 'Admin',
], function () {
	   Route::crud('user', 'UserCrudController');
	   Route::get('dashboard', 'DashboardController@index');

    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
});

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],
], function () {
    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::post('emergency-item/send-emg-notification','AjaxController@sendEmgNotification');
    Route::get('project/show-report-summary/{id}','AjaxController@showSummaryReport');
});

// middleware

app/Models/Contact_pdma.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Contact_pdma extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'contact_pdma';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */
    public function getNgoName() {
        if($this->ngo){
            return $this->ngo->name;
        }else{
            return '';
        }
     }
    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    public function ngo()
    {
        return $this->belongsTo('App\User','ngo_id','id');
    }
    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/ContactPdmaController.php
<?php

namespace App\Http\Controllers;

use App\Models\NgoProfile;
use Illuminate\Http\Request;
use Auth;
use App\Models\Contact_pdma;

class ContactPdmaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding PDMA Contacts.');
        }
        $Contact_pdma = Contact_pdma::where('ngo_id', $userId)->get();
        return view('Contact_pdma.index', compact('Contact_pdma','ngoProfile'));
    }

    public function create()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding PDMA Contacts.');
        }
        return view('Contact_pdma.add');
    }

    public function edit($id)
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding PDMA Contacts.');
        }
        $Contact_pdma = Contact_pdma::where('id', $id)->first();
        return view('Contact_pdma.Edit', compact('Contact_pdma'));
    }


    public function store(Request $request)
    {
         $request->validate([
            'cell_1' => 'required',
            'email_1' => 'required',

            ]);
        $userId = Auth::id();

        $Contact_pdma = new Contact_pdma([
            'cell_1' => $request->get('cell_1'),
            'cell_2' => $request->get('cell_2'),
            'email_1' => $request->get('email_1'),
            'email_2' => $request->get('email_2'),
            'ngo_id' => $userId,
        ]);
       $Contact_pdma->save();
       return redirect('/contacpdma')->with('message', 'Saved!');
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'cell_1' => 'required',
            'email_1' => 'required',
            ]);

        $Contact_pdma = Contact_pdma::find($id);
        $Contact_pdma->cell_1 =  $request->get('cell_1');
        $Contact_pdma->cell_2 =  $request->get('cell_2');
        $Contact_pdma->email_1 =  $request->get('email_1');
        $Contact_pdma->email_2 =  $request->get('email_2');

        $Contact_pdma->save();
        return redirect('/contacpdma')->with('message', 'Update successfully!');
    }

    public function delete($id){

        $userId = Auth::id();
        $Contact_pdma = Contact_pdma::where('id', $id)->where('ngo_id',$userId)->first();
        if($Contact_pdma){
            $Contact_pdmaDelete = Contact_pdma::find($Contact_pdma->id);
            $Contact_pdmaDelete->delete();

        }

        return redirect('/contacpdma')->with('message', 'Deleted successfully!');    }
}

resources/views/Contact_pdma/Edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>
                <div class="panel-body">
                    @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div><br />
                                @endif
                    <form action="{{route('contacpdma.update',$Contact_pdma->id)}}" class="needs-validation" novalidate method="POST" enctype="multipart/form-data">
                        @method('PATCH')

                        @csrf

                    <div class="form-group col-md-6">
                        <label for="cell_1">Cell 1 *</label>
                        <input required type="text" class="form-control is_numeric" id="cell_1" placeholder="Cell 1" value="{{$Contact_pdma->cell_1}}" name="cell_1">
                </div>
                <div class="form-group col-md-6">
                    <label for="cell_2">Cell 2</label>
                    <input type="text" class="form-control is_numeric" id="cell_2" placeholder="Cell 2" value="{{$Contact_pdma->cell_2}}" name="cell_2">
                </div>

                    <div class="form-group col-md-6">
                        <label for="email_1">Email 1 *</label>
                        <input required type="email" class="form-control" id="email_1" placeholder="example@gmail.com" value="{{$Contact_pdma->email_1}}"  name="email_1">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="email_2">Email 2</label>
                        <input type="email" class="form-control" id="email_2" placeholder="example@gmail.com" value="{{$Contact_pdma->email_2}}"  name="email_2">
                    </div>



                        <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-default">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('pagespecificscripts')
    <script>
        // Disable form submissions if there are invalid fields
        (function() {
            'use strict';
            window.addEventListener('load', function() {

                // Get the forms we want to add validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
@endsection

resources/views/Contact_pdma/add.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{-- <div class="card-title">
                        <div class="title">Basic example</div>
                    </div> --}}
                </div>
                <div class="panel-body">
                    @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div><br />
                                @endif
                    <form action="{{route('contacpdma.store')}}" class="needs-validation" novalidate method="POST" enctype="multipart/form-data">
                        @csrf
                    <div class="form-group col-md-6">
                            <label for="cell_1">Cell 1 *</label>
                            <input required type="text" class="form-control is_numeric" id="cell_1" placeholder="Cell 1" value="{{old('cell_1')}}" name="cell_1">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="cell_2">Cell 2</label>
                        <input type="text" class="form-control is_numeric" id="cell_2" placeholder="Cell 2" value="{{old('cell_2')}}" name="cell_2">
                    </div>

                        <div class="form-group col-md-6">
                            <label for="email_1">Email 1 *</label>
                            <input required type="email" class="form-control" id="email_1" placeholder="example@gmail.com" value="{{old('email_1')}}"  name="email_1">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="email_2">Email 2</label>
                            <input type="email" class="form-control" id="email_2" placeholder="example@gmail.com" value="{{old('email_2')}}"  name="email_2">
                        </div>

                        <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('pagespecificscripts')
<script>
    // Disable form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {

            // Get the forms we want to add validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
@endsection

resources/views/Contact_pdma/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-md-12">
        <!-- Advanced Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Contact For PDMA
            </div>
            <div class="panel-body">
                @if (session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif


                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Cell 1</th>
                                <th>Cell 2</th>
                                <th>Email 1</th>
                                <th>Email 2</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($Contact_pdma as $key => $item)
                            <tr class="odd gradeX">
                                <td>{{$item->cell_1}}</td>
                                <td>{{$item->cell_2}}</td>
                                <td>{{$item->email_1}}</td>
                                <td>{{$item->email_2}}</td>
                                <td>
                                    @if((checkProfileApproval() && checkEnableEdit()) || $ngoProfile->user->status === 0 )
                                    <a href="{{ url("/contacpdma/{$item->id}/edit") }}">Edit</a>
                                    @endif

                                    @if($ngoProfile->user->status === 0 )
                                        - <a href="{{ url("/contacpdma/{$item->id}/delete") }}">Delete</a>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr class="gradeU">
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                                <td>-</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!--End Advanced Tables -->
    </div>
</div>

@endsection

@section('pagespecificscripts')
<script>
       $(document).ready(function () {
                $('#dataTables-example').dataTable();
            });
    </script>
@endsection