routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
Auth::routes(['verify' => true]);


Route::get('user-profile', 'UserProfileController@index');
Route::post('user-profile', 'UserProfileController@store')->name('user-profile');


Route::middleware(['auth','verified','roleCheck:NGO'])->group(function () {

	Route::get('/', 'HomeController@index')->name('home');


	Route::get('/home', 'HomeController@index')->name('home');
	// Route::get('/volunteers', 'VolunteersController@index')->name('volunteers');
	Route::resource('volunteers', 'VolunteersController');
//	Route::resource('/admin/hazard_prone_area', 'HazardProneAreaController');
	Route::get('/volunteers/{id}/delete', 'VolunteersController@delete');
	Route::resource('stocks', 'StocksController');
	Route::get('/stocks/{id}/delete', 'StocksController@delete');
    Route::get('/stocks/detail/{id}', 'StocksController@show');
	Route::resource('affiliations', 'AffiliationsController');
	Route::get('/affiliations/{id}/delete', 'AffiliationsController@delete');
    Route::get('/affiliations/detail/{id}', 'AffiliationsController@show');



	//NGO Profile
    Route::get('/profile/request-approval', 'Ngo\NgoProfileController@approval');
    Route::get('/profile/create','Ngo\NgoProfileController@create');
    Route::post('/profile/create','Ngo\NgoProfileController@store')->name('profile.store');
    Route::get('/profile/approval/request-update', 'Ngo\NgoProfileController@update_approval');
	Route::resource('profile','Ngo\NgoProfileController');

	//NGO MOU
	Route::resource('mous','Ngo\NgoMouController');
	Route::get('/mou/create','Ngo\NgoMouController@create');
    Route::get('/mou/{id}/delete', 'Ngo\NgoMouController@delete');

	//NGO Projects
	Route::resource('projects','Ngo\NgoProjectsController');
	Route::get('/project/create','Ngo\NgoProjectsController@create');
    Route::get('/noc/approval/request-update', 'Ngo\NgoProjectsController@update_approval');
	Route::get('/project/{id}/delete', 'Ngo\NgoProjectsController@delete');


	//NGO Donors
	Route::resource('donors','Ngo\NgoDonorsController');

	//NGO NOC Requests
	Route::resource('noc-requests','Ngo\NgoNocRequestsController');
    Route::get('/noc-apply/create','Ngo\NgoProjectsController@nocApply');

	//Emergencies Responded
	Route::resource('past-emergencies','Ngo\NgoPastEmergenciesController');
	Route::get('/past-emergency/create','Ngo\NgoPastEmergenciesController@create');
	Route::get('/past-emergency/{id}/delete','Ngo\NgoPastEmergenciesController@delete');
    Route::get('/past-emergency/detail/{id}', 'Ngo\NgoPastEmergenciesController@show');

	//NGO Contact
	Route::resource('ngocontact', 'NgoContactController');
	Route::get('ngocontact/{id}/delete', 'NgoContactController@delete');
    Route::get('ngocontact/detail/{id}', 'NgoContactController@show');

	//Contact For PDMA
	Route::resource('contacpdma', 'ContactPdmaController');
	Route::get('contacpdma/{id}/delete', 'ContactPdmaController@delete');


	// Emergencies
	Route::get('emergencies', 'EmergenciesController@index');
	// Route::get('need-assesment', 'NeedAssesmentController@index');
	Route::resource('need-assesment', 'NeedAssesmentController');
	Route::post('needassesmentresponses', 'NeedAssesmentController@needassesmentresponses')->name('needassesmentresponses');


	//Risk Management
	Route::resource('risk-management', 'RiskManagementController');
	Route::get('risk-management/{id}/delete', 'RiskManagementController@delete');

	//Reaminder
	Route::get('readremainder/{id}', 'HomeController@readremainder')->name('readremainder');


	Route::resource('human-resource', 'HumanResourceController');
	Route::get('/human-resource/{id}/delete', 'HumanResourceController@delete');
	Route::get('/human-resource/detail/{id}', 'HumanResourceController@show');



	//NGO Reporting
	Route::resource('reporting','Ngo\NgoReportingController');
	Route::get('/reporting/create','Ngo\NgoReportingController@create')->name('reporting.new');
	Route::get('/reporting/{id}/delete', 'Ngo\NgoReportingController@delete');


	// Notification Listing
	Route::get('notification','Ngo\NotificationController@index')->name('notification.index');
	Route::get('notification/emergencies','Ngo\NotificationController@emergencies')->name('notification.emergencies');

	// Tehsil Listing
    Route::get('/getTehsils/{id}','AjaxController@getTehsils');
    Route::get('/getUcs/{id}','AjaxController@getUcs');
    Route::get('/getProjectDetail/{id}','AjaxController@getProjectDetail');
    Route::post('accept-terms/{id}','AjaxController@acceptTerms');


});

Route::resource('admin/comments', 'CommentController');

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],

    'namespace'  => 'Admin',
], function () {
	   Route::crud('user', 'UserCrudController');
	   Route::get('dashboard', 'DashboardController@index');

    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
});

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', 'RequireAdminRole', config('backpack.base.middleware_key', 'admin')],
], function () {
    Route::get('api/getTehsils','AjaxController@getTehsilsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::get('api/getUcs','AjaxController@getUcsBackpack');
    Route::post('emergency-item/send-emg-notification','AjaxController@sendEmgNotification');
    Route::get('project/show-report-summary/{id}','AjaxController@showSummaryReport');
});

// middleware

app/Http/Controllers/Ngo/NgoDonorsController.php
<?php

namespace App\Http\Controllers\Ngo;

use App\Http\Controllers\Controller;

use App\Models\NgoProjects;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\NgoProfile;
use Auth;
use Illuminate\Support\Facades\Validator;

class NgoDonorsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Donors.');
        }
        $projects = $ngoProfile->projects->where('status',1);
        return view('ngo.donors.index', compact('ngoProfile','projects'));
    }

    public function edit($id)
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Donors.');
        }
        $project = NgoProjects::findOrFail($id);
        return view('ngo.donors.edit', compact('ngoProfile','project'));
    }

    public function update(Request $request, $id){
        $validator = Validator::make($request->all(),[
            'funds_donor_name' => 'required',
            'funds_amount' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect(route('donors.edit',$id))
                ->withErrors($validator)
                ->withInput();
        }

        $data = $request->all();

        try{
            $projectData =   NgoProjects::find($id);
            if(!$projectData)
                return redirect(route('donors.index'))->with('message', 'error|Project with id '.$id.' not exist.');

            $projectData->update($data);
        }catch (\Exception $e){
            // do task when error
            return redirect(route('donors.edit',$id))
                ->withErrors($e->getMessage())
                ->withInput();
        }
        return redirect('/donors')->with('message', 'success|Donor updated successfully.');
    }
}

app/Http/Controllers/Ngo/NgoMouController.php
<?php

namespace App\Http\Controllers\Ngo;

use App\Http\Controllers\Controller;
use App\Models\FundingAgency;
use App\Models\NgoMou;
use App\Models\OrganizationNatures;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\Models\NgoProfile;
use Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class NgoMouController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding MOU.');
        }
        $mouData = $ngoProfile->mous;
        return view('ngo.mou.index', compact('ngoProfile','mouData'));
    }

    public function create(){
        $userId = Auth::user()->id;
        /*$fundingAgency = FundingAgency::all();
        $orgNatures = OrganizationNatures::all();*/
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding MOU.');
        }
        return view('ngo.mou.create', compact('userId','ngoProfile'));
    }

    public function edit($id){
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'warning|Profile doesn\'t exists.');
        }
        $mou = NgoMou::findOrFail($id);
        return view('ngo.mou.edit', compact('ngoProfile','mou','userId'));
    }

    public function store(Request $request)
    {
        // $validator = Validator::make($request->all(),[
        //     'mou_status' => 'required_if:have_mou,1',
        //     'mou_expiry_date' => 'required_if:have_mou,1',
        //     'mou_file' => 'mimes:doc,pdf,docx,jpg,jpeg'
        // ]);
        $validator = Validator::make($request->all(),[
            'mou_status' => 'required',
            'mou_expiry_date' => 'required_if:mou_status,valid,invalid',
            'mou_file' => 'mimes:doc,pdf,docx,jpg,jpeg'
        ]);

        if ($validator->fails()) {
            return redirect('mous/create')
                ->withErrors($validator)
                ->withInput();
        }

        $userId = Auth::user()->id;
        DB::beginTransaction();
        try{
            $datMou = $request->all();
            $datMou['mou_signed_date'] = Carbon::parse($request->mou_signed_date);
            if($request->mou_expiry_date){
                $datMou['mou_expiry_date'] = Carbon::parse($request->mou_expiry_date);
            }
            $mouData = new NgoMou($datMou);
            $mouData->ngo()->associate($userId);
            $mouData->save();
            //if($mouData){
                $disks = 'uploads_dir';
                $fileName = '';
                if ($request->hasFile('mou_file') && $request->file('mou_file')->isValid()) {
                    /*$name = $request->file('mou_file');
                    $fileName = str_replace(' ', '_', pathinfo($name->getClientOriginalName())['filename']).'_'.time() . '.' . $name->getClientOriginalExtension();

                    $fileSystem = \Storage::disk($disks);
                    $filePath = 'mou/' . $request->ngo_id . '/contents/' . $fileName;
                    $fileSystem->put($filePath, file_get_contents($request->file('mou_file')), 'public');
                    $mouData->mou_file = $filePath;
                    $mouData->update();*/

                    $name = $request->file('mou_file');
                    $destinationPath = 'uploads/mous/' . $request->ngo_id . '/contents/';
                    $fileName = str_replace(' ', '_', pathinfo($name->getClientOriginalName())['filename']).'_'.time() . '.' . $name->getClientOriginalExtension();
                    $request->file('mou_file')->move($destinationPath, $fileName);
                    $mouData->mou_file = $destinationPath.'/'.$fileName;
                    $mouData->update();
                }
            DB::commit();
            //}
        }catch (\Exception $e){
            // do task when error
            DB::rollBack();
            // do task when error
            return redirect('mous/create')
                ->withErrors($e->getMessage())
                ->withInput();
        }
        return redirect('/mous')->with('message', 'success|MOU data saved.');
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),[
            'mou_status' => 'required',
            'mou_expiry_date' => 'required_if:mou_status,valid,invalid',
            'mou_file' => 'mimes:doc,pdf,docx,jpg,jpeg'
        ]);

        if ($validator->fails()) {
            return redirect(route('mous.edit',$id))
                ->withErrors($validator)
                ->withInput();
        }

        $datMou = $request->all();
        $datMou['mou_signed_date'] = Carbon::parse($request->mou_signed_date);
        if($request->mou_expiry_date){
            $datMou['mou_expiry_date'] = Carbon::parse($request->mou_expiry_date);
        }

        try{
            $mouData =   NgoMou::find($id);
            if(!$mouData)
                return redirect(route('mous.index'))->with('message', 'error|MOU with id '.$id.' not exist.');

            $mouData->update($datMou);

            $disks = !empty(\Config::get('filesystems.default'))?\Config::get('filesystems.default'):'local';

            if ($request->hasFile('mou_file') && $request->file('mou_file')->isValid()) {
                /*$name = $request->file('mou_file');
                $fileName = str_replace(' ', '_', pathinfo($name->getClientOriginalName())['filename']).'_'.time() . '.' . $name->getClientOriginalExtension();

                $fileSystem = \Storage::disk($disks);
                $filePath = 'mou/' . $mouData->ngo_id . '/contents/' . $fileName;
                $fileSystem->put($filePath, file_get_contents($request->file('mou_file')), 'public');
                $mouData->mou_file = $filePath;
                $mouData->update();*/

                $name = $request->file('mou_file');
                $destinationPath = 'uploads/mous/' . $mouData->ngo_id . '/contents/';
                $fileName = str_replace(' ', '_', pathinfo($name->getClientOriginalName())['filename']).'_'.time() . '.' . $name->getClientOriginalExtension();
                $request->file('mou_file')->move($destinationPath, $fileName);
                $mouData->mou_file = $destinationPath.'/'.$fileName;
                $mouData->update();
            }
        }catch (\Exception $e){
            // do task when error
            return redirect(route('mous.edit',$id))
                ->withErrors($e->getMessage())
                ->withInput();
        }

        return redirect('/mous')->with('message', 'success|MOU data updated.');
    }

    public function delete($id){

        $userId = Auth::id();
        $mou = NgoMou::where('id', $id)->where('ngo_id',$userId)->first();
        if($mou){
            $mouDelete = NgoMou::find($mou->id);
            $mouDelete->delete();

        }

        return redirect('/mous')->with('message', 'success|Deleted successfully!');
    }

}

app/Http/Controllers/Ngo/NgoNocRequestsController.php
<?php

namespace App\Http\Controllers\Ngo;

use App\Http\Controllers\Controller;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\NgoProfile;
use Auth;
use Illuminate\Support\Facades\Validator;

class NgoNocRequestsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $ngoProfile = NgoProfile::where('user_id', $userId)->first();
        if(!isset($ngoProfile) && $ngoProfile === null){
            return redirect('/profile/create')->with('message', 'error|NGO Profile should exist before adding Projects.');
        }
        $projects = $ngoProfile->projects->where('status',1);
        return view('ngo.noc.index', compact('ngoProfile','projects'));
    }
}

resources/views/ngo/reporting/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            @if (session()->has('message'))
                {!! displayMessage() !!}
            @endif
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    Reporting
                </div>
                <div class="panel-body">
                    @if(isset($ngoProfile) && $ngoProfile == null)
                        <div>
                            You need to complete your profile first. Click <a href="{{url('/profile/create')}}">here</a> to fill in your details.
                        </div>
                    @else
                        <div class="row">
                            <div class="col-md-3">
                                <select name="report_duration" id="report_duration" class="form-control">
                                    <option value="">--Select Report Duration--</option>
                                    <option value="monthly">Monthly</option>
                                    <option value="quarterly">Quarterly</option>
                                    <option value="final">Final</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <select name="project_title" id="project_title" class="form-control">
                                    <option value="">--Select Project--</option>

                                    @foreach ($ngoProjects  as $project)
                                        <option value="{!!$project->project_title!!}">{!!$project->project_title!!}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="projects-table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Project Title</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Owner Name</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                    <th>Duration</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse ($reporting as $key => $item)
                                    <tr class="odd gradeX">
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->project_title}}</td>
                                        <td>{{$item->start_date}}</td>
                                        <td>{{$item->end_date}}</td>
                                        <td>{{$item->project_owner_name}}</td>
                                        <td>{{($item->report_status == '1')?'Current':'Ongoing'}}</td>
                                         <td>
                                             <a href="{{ route('reporting.show', $item->id) }}">View</a>
                                             @if(checkProfileApproval() && checkEnableEdit())
                                             <a href="{{ route('reporting.edit', $item->id)}}">Edit</a>
                                             @endif
                                             @if($ngoProfile->user->status === 0 )
                                                 - <a href="{{ url("/reporting/{$item->id}/delete") }}">Delete</a>
                                             @endif
                                         </td>
                                        <td>{{$item->report_duration}}</td>
                                    </tr>
                                @empty
                                    <tr class="gradeU">
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    @endif
                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>

@endsection
@section('pagespecificscripts')
    <script src="{{ asset('assets/js/filterDropDown.js') }}"></script>
    <script>
        $(document).ready(function () {
            oTableContact = $('#projects-table').DataTable({
                "columnDefs": [
                    {
                        "targets": [7],
                        "visible": false
                    }
                ]
            });

            $('#report_duration').change(function () {
                oTableContact.column('7').search($(this).val()).draw();
            });
            $('#project_title').change(function () {
                oTableContact.column('1').search($(this).val()).draw();
            });
        });
    </script>
@endsection